### ISSUE TITLE
Batch size 1 and 2

### ISSUE THREAD

**Issue by ethancohen123** [IlyaTrofimov/MTopDiv#2]
Hi 
Is there a minimal amount of generated/true images point clouds to get this work correctly ?
In your experiment you are using 10^3 and 10^4 for ffhq, I was wondering if it possible to lower those numbers (like Bq=100 and Bp=1000 where p is the data distribution and q the model distribution )
Thanks

**Comment by IlyaTrofimov** [comment]
Hi, we used large batch sizes (10^3 and 10^4) for complex datasets like FFHQ.
For more simple datasets, with lower feature dimensionality, smaller batch sizes (10^2 and 10^3) should be fine.
Also pls. note that for point clouds comparison in practice we recommend to use 0.5 * (mtopdiv(p,q) + mtopdiv(q,p))
because you don't know apriori if mtopdiv(p,q) or mtopdiv(q,p) will work well.
